/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_gl2jni_GL2JNILib */

#ifndef _Included_com_android_gl2jni_GL2JNILib
#define _Included_com_android_gl2jni_GL2JNILib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_gl2jni_GL2JNILib
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNILib_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_android_gl2jni_GL2JNILib
 * Method:    loadObjModel
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNILib_loadObjModel
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     com_android_gl2jni_GL2JNILib
 * Method:    setRenderBufferSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNILib_setRenderBufferSize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_android_gl2jni_GL2JNILib
 * Method:    frame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNILib_frame
  (JNIEnv *, jclass);

/*
 * Class:     com_android_gl2jni_GL2JNILib
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNILib_reset
  (JNIEnv *, jclass);

/*
 * Class:     com_android_gl2jni_GL2JNILib
 * Method:    setDocDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNILib_setDocDirectory
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_android_gl2jni_GL2JNILib
 * Method:    setGLSLDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNILib_setGLSLDirectory
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_android_gl2jni_GL2JNILib
 * Method:    rotate
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNILib_rotate
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     com_android_gl2jni_GL2JNILib
 * Method:    translate
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNILib_translate
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     com_android_gl2jni_GL2JNILib
 * Method:    scale
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNILib_scale
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     com_android_gl2jni_GL2JNILib
 * Method:    setBackgroundColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNILib_setBackgroundColor
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_android_gl2jni_GL2JNILib
 * Method:    setModelColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNILib_setModelColor
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_android_gl2jni_GL2JNILib
 * Method:    setCameraPosition
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNILib_setCameraPosition
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     com_android_gl2jni_GL2JNILib
 * Method:    setLightPosition
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNILib_setLightPosition
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     com_android_gl2jni_GL2JNILib
 * Method:    setLigthDirection
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNILib_setLigthDirection
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     com_android_gl2jni_GL2JNILib
 * Method:    setAmbientColor
 * Signature: (ZZZ)V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNILib_setAmbientColor
  (JNIEnv *, jclass, jboolean, jboolean, jboolean);

/*
 * Class:     com_android_gl2jni_GL2JNILib
 * Method:    setDiffuseColor
 * Signature: (ZZZ)V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNILib_setDiffuseColor
  (JNIEnv *, jclass, jboolean, jboolean, jboolean);

/*
 * Class:     com_android_gl2jni_GL2JNILib
 * Method:    enableTexture
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_GL2JNILib_enableTexture
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
